### ISSUE TITLE
Other Discovery Methods

### ISSUE THREAD

**Issue by DerekTBrown** [Runnable/swarmerode#13]
As I understand it, Swarmerode only works with a single discovery backend- consul.  Are there plans to implement swarmerode for etcd or other discovery methods?

**Comment by bkendall** [comment]
That is correct: swarmerode currently only works with consul. Because this is something that we are using internally, it's heavily bias towards that consul.

I would be happy to help consider a more general implementation of some functions to be more flexible and use consul if information was provided. This would extend nicely into being able to source other backends directly as well. However, this isn't going to be a top priority for us. PRs are always welcome, and I'd be happy to share insight and feedback on them!
